import { useState, useMemo } from 'react'
import {
  FileText, Download, Calendar, Filter, CheckCircle2,
  Clock, Shield, ArrowUpRight, Plus, RefreshCw, Eye,
  Printer, Search, X, Check, Database, HardDrive, Layers
} from 'lucide-react'
import toast from 'react-hot-toast'
import {
  generateExecutiveReportHTML,
  generateAlertsAuditReportHTML,
  downloadReportPDF,
  downloadReportHTML,
  openReportPrintWindow,
  downloadCSV,
} from '../utils/reportTemplateGenerator'

const INITIAL_REPORTS = [
  {
    id: 'REP-2026-0929',
    title: 'Daily Fleet Failure Risk & Predictive Dispatch Brief',
    category: 'Operational',
    generated_at: '2026-09-29 08:00:00',
    generated_by: 'FleetSentinel AI Automated Cron',
    format: 'PDF',
    size: '2.4 MB',
    status: 'READY',
    type: 'executive',
  },
  {
    id: 'REP-2026-0928',
    title: 'Weekly 100k Connected Vehicle Health & Ingestion Audit',
    category: 'Executive',
    generated_at: '2026-09-28 23:59:00',
    generated_by: 'DevOps / Reliability Team',
    format: 'PDF',
    size: '8.1 MB',
    status: 'READY',
    type: 'executive',
  },
  {
    id: 'REP-2026-0925',
    title: 'High-Dimensional Vector Fingerprint Accuracy Report',
    category: 'ML Research',
    generated_at: '2026-09-25 14:30:00',
    generated_by: 'MLOps Service',
    format: 'CSV',
    size: '14.2 MB',
    status: 'READY',
    type: 'csv',
  },
  {
    id: 'REP-2026-0920',
    title: 'Monthly EV Battery Degradation & SOH Benchmark',
    category: 'EV Fleet',
    generated_at: '2026-09-20 10:15:00',
    generated_by: 'EV Fleet Operations',
    format: 'PDF',
    size: '4.8 MB',
    status: 'READY',
    type: 'executive',
  },
  {
    id: 'REP-2026-0915',
    title: 'Preventive Downtime Cost Savings & ROI Ledger',
    category: 'Financial',
    generated_at: '2026-09-15 09:00:00',
    generated_by: 'Finance & Asset Management',
    format: 'CSV',
    size: '1.2 MB',
    status: 'READY',
    type: 'csv',
  },
]

export default function ReportsPage() {
  const [reports, setReports] = useState(INITIAL_REPORTS)
  const [selectedCategory, setSelectedCategory] = useState('ALL')
  const [searchQuery, setSearchQuery] = useState('')
  const [generating, setGenerating] = useState(false)
  
  // Modals
  const [showGenerateModal, setShowGenerateModal] = useState(false)
  const [previewReport, setPreviewReport] = useState(null)
  
  // New Report Form state
  const [newTitle, setNewTitle] = useState('Daily Fleet Failure Risk & Predictive Dispatch Brief')
  const [newCategory, setNewCategory] = useState('Operational')
  const [newScope, setNewScope] = useState('All Fleets (100,000 Connected Commercial Vehicles)')
  const [newFormat, setNewFormat] = useState('PDF')

  // Filtered reports
  const filtered = useMemo(() => {
    return reports.filter(r => {
      const matchCat = selectedCategory === 'ALL' || r.category === selectedCategory
      const matchSearch = !searchQuery ||
        r.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        r.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
        r.generated_by.toLowerCase().includes(searchQuery.toLowerCase())
      return matchCat && matchSearch
    })
  }, [reports, selectedCategory, searchQuery])

  // Generate Report HTML content for a specific report object
  const getReportHTML = (rep) => {
    return generateExecutiveReportHTML({
      id: rep.id,
      title: rep.title,
      generatedAt: rep.generated_at,
      generatedBy: rep.generated_by,
      scope: rep.scope || 'All Fleets (100,000 Connected Commercial Vehicles)',
    })
  }

  // Handle Preview
  const handleOpenPreview = (rep) => {
    if (rep.format === 'CSV') {
      toast('CSV file preview: Please click Download to inspect raw tabular data.', { icon: '📊' })
      return
    }
    const html = getReportHTML(rep)
    setPreviewReport({ ...rep, html })
  }

  // Handle Print/PDF
  const handlePrint = (rep) => {
    if (rep.format === 'CSV') {
      toast.error('CSV datasets cannot be printed directly as executive PDF packages.')
      return
    }
    const html = getReportHTML(rep)
    openReportPrintWindow(html)
    toast.success(`Opening ${rep.id} print dialog`)
  }

  // Handle Download (PDF or CSV)
  const handleDownload = async (rep) => {
    if (rep.format === 'CSV') {
      const sampleCSV = `Report ID,Title,Category,Generated At,Generated By,Monitored Vehicles,Status\n"${rep.id}","${rep.title}","${rep.category}","${rep.generated_at}","${rep.generated_by}","100000","READY"\n`
      downloadCSV(`${rep.id}_Dataset.csv`, sampleCSV)
      toast.success(`Downloaded ${rep.id}.csv`)
    } else {
      const html = getReportHTML(rep)
      await downloadReportPDF(`${rep.id}_Executive_Audit.pdf`, html)
    }
  }

  // Handle Creation of New Audit Report
  const handleConfirmGenerate = () => {
    setGenerating(true)
    setTimeout(() => {
      setGenerating(false)
      const newId = `REP-2026-${Math.floor(1000 + Math.random() * 9000)}`
      const newRep = {
        id: newId,
        title: newTitle,
        category: newCategory,
        scope: newScope,
        generated_at: new Date().toISOString().replace('T', ' ').slice(0, 19),
        generated_by: 'Fleet Operations Director (admin)',
        format: newFormat,
        size: newFormat === 'PDF' ? '3.4 MB' : '1.8 MB',
        status: 'READY',
        type: newFormat === 'PDF' ? 'executive' : 'csv',
      }
      setReports(prev => [newRep, ...prev])
      setShowGenerateModal(false)
      toast.success(`Audit Report ${newId} compiled and verified!`)
    }, 1200)
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20, paddingTop: 4 }}>
      {/* ── Page Header ─────────────────────────────────────────── */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 14 }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <h1 style={{ fontSize: 24, fontWeight: 800, color: 'var(--text-primary)', letterSpacing: '-0.02em', margin: 0 }}>
              Compliance & Operational Reports
            </h1>
            <span style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 5,
              background: '#F0FDF4',
              border: '1px solid #BBF7D0',
              color: '#16A34A',
              fontSize: 11.5,
              fontWeight: 700,
              padding: '2px 8px',
              borderRadius: 999,
            }}>
              <CheckCircle2 size={12} /> Audit Compliant (ISO 26262)
            </span>
          </div>
          <p style={{ color: 'var(--text-secondary)', fontSize: 13, marginTop: 4, marginBottom: 0 }}>
            Audit-grade maintenance logs, failure prediction records, and executive fleet performance packages.
          </p>
        </div>

        <button
          onClick={() => setShowGenerateModal(true)}
          style={{
            padding: '9px 16px',
            borderRadius: 8,
            background: '#2563EB',
            border: 'none',
            color: '#FFFFFF',
            fontSize: 13,
            fontWeight: 600,
            cursor: 'pointer',
            display: 'inline-flex',
            alignItems: 'center',
            gap: 7,
            boxShadow: '0 1px 3px rgba(37,99,235,0.3)',
            transition: 'background 0.15s ease',
          }}
        >
          <Plus size={15} /> Generate New Audit Report
        </button>
      </div>

      {/* ── KPI Summary Cards ───────────────────────────────────── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 14 }}>
        <div style={{
          background: '#FFFFFF',
          border: '1px solid #E2E8F0',
          borderRadius: 12,
          padding: '16px 20px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
          borderLeft: '4px solid #2563EB',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: '#64748B', fontSize: 12, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.04em' }}>
            <span>Available Audit Packages</span>
            <FileText size={16} color="#2563EB" />
          </div>
          <div style={{ fontSize: 26, fontWeight: 800, color: '#0F172A', marginTop: 8 }}>
            {reports.length}
          </div>
          <div style={{ fontSize: 12, color: '#64748B', marginTop: 4 }}>
            Ready for instant download & print
          </div>
        </div>

        <div style={{
          background: '#FFFFFF',
          border: '1px solid #E2E8F0',
          borderRadius: 12,
          padding: '16px 20px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
          borderLeft: '4px solid #16A34A',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: '#64748B', fontSize: 12, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.04em' }}>
            <span>Audit Readiness Score</span>
            <Shield size={16} color="#16A34A" />
          </div>
          <div style={{ fontSize: 26, fontWeight: 800, color: '#16A34A', marginTop: 8 }}>
            99.8%
          </div>
          <div style={{ fontSize: 12, color: '#64748B', marginTop: 4 }}>
            ASIL-D cryptographic verification
          </div>
        </div>

        <div style={{
          background: '#FFFFFF',
          border: '1px solid #E2E8F0',
          borderRadius: 12,
          padding: '16px 20px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
          borderLeft: '4px solid #7C3AED',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: '#64748B', fontSize: 12, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.04em' }}>
            <span>Automated Cron Jobs</span>
            <Clock size={16} color="#7C3AED" />
          </div>
          <div style={{ fontSize: 26, fontWeight: 800, color: '#7C3AED', marginTop: 8 }}>
            4 Active
          </div>
          <div style={{ fontSize: 12, color: '#64748B', marginTop: 4 }}>
            Daily, Weekly & Monthly dispatches
          </div>
        </div>

        <div style={{
          background: '#FFFFFF',
          border: '1px solid #E2E8F0',
          borderRadius: 12,
          padding: '16px 20px',
          boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
          borderLeft: '4px solid #EA580C',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', color: '#64748B', fontSize: 12, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.04em' }}>
            <span>Archive Storage Quota</span>
            <HardDrive size={16} color="#EA580C" />
          </div>
          <div style={{ fontSize: 26, fontWeight: 800, color: '#0F172A', marginTop: 8 }}>
            31.7 MB
          </div>
          <div style={{ fontSize: 12, color: '#64748B', marginTop: 4 }}>
            Cloud encrypted bucket (500 MB quota)
          </div>
        </div>
      </div>

      {/* ── Filter & Search Toolbar ─────────────────────────────── */}
      <div
        style={{
          padding: '14px 18px',
          background: '#FFFFFF',
          border: '1px solid #E2E8F0',
          borderRadius: 12,
          boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexWrap: 'wrap',
          gap: 12,
        }}
      >
        {/* Search */}
        <div style={{ position: 'relative', flex: 1, minWidth: 260 }}>
          <Search size={15} style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', color: '#94A3B8' }} />
          <input
            placeholder="Search report title, ID (e.g. REP-2026-0929), or author..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            style={{
              width: '100%',
              padding: '9px 34px 9px 34px',
              fontSize: 13,
              borderRadius: 8,
              background: '#F8FAFC',
              border: '1px solid #E2E8F0',
              color: '#0F172A',
              outline: 'none',
              boxSizing: 'border-box',
            }}
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery('')}
              style={{ position: 'absolute', right: 10, top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', color: '#94A3B8', cursor: 'pointer' }}
            >
              <X size={14} />
            </button>
          )}
        </div>

        {/* Category Pills */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 4, background: '#F8FAFC', padding: 4, borderRadius: 8, border: '1px solid #E2E8F0' }}>
          <span style={{ fontSize: 11, fontWeight: 700, color: '#64748B', padding: '0 6px' }}>CATEGORY:</span>
          {['ALL', 'Operational', 'Executive', 'ML Research', 'EV Fleet', 'Financial'].map(cat => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              style={{
                background: selectedCategory === cat ? '#2563EB' : 'transparent',
                border: 'none',
                color: selectedCategory === cat ? '#FFFFFF' : '#475569',
                fontSize: 12,
                fontWeight: 600,
                padding: '5px 11px',
                borderRadius: 6,
                cursor: 'pointer',
                transition: 'all 0.15s ease',
              }}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* ── Reports Table ───────────────────────────────────────── */}
      <div
        style={{
          background: '#FFFFFF',
          border: '1px solid #E2E8F0',
          borderRadius: 12,
          boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
          overflow: 'hidden',
        }}
      >
        <div
          style={{
            padding: '14px 20px',
            borderBottom: '1px solid #E2E8F0',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            background: '#FFFFFF',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, color: '#0F172A', margin: 0 }}>Official Report Archive</h3>
            <span style={{ fontSize: 12, color: '#64748B', background: '#F1F5F9', padding: '2px 8px', borderRadius: 999, fontWeight: 500 }}>
              Showing {filtered.length} of {reports.length} records
            </span>
          </div>
        </div>

        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
            <thead>
              <tr style={{ background: '#F8FAFC', borderBottom: '1px solid #E2E8F0' }}>
                <th style={{ padding: '12px 18px', fontSize: 11.5, fontWeight: 700, color: '#64748B', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Report ID & Title</th>
                <th style={{ padding: '12px 14px', fontSize: 11.5, fontWeight: 700, color: '#64748B', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Category</th>
                <th style={{ padding: '12px 14px', fontSize: 11.5, fontWeight: 700, color: '#64748B', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Generated Timestamp</th>
                <th style={{ padding: '12px 14px', fontSize: 11.5, fontWeight: 700, color: '#64748B', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Author / Service</th>
                <th style={{ padding: '12px 14px', fontSize: 11.5, fontWeight: 700, color: '#64748B', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Format</th>
                <th style={{ padding: '12px 14px', fontSize: 11.5, fontWeight: 700, color: '#64748B', textTransform: 'uppercase', letterSpacing: '0.04em' }}>Status</th>
                <th style={{ padding: '12px 18px', fontSize: 11.5, fontWeight: 700, color: '#64748B', textTransform: 'uppercase', letterSpacing: '0.04em', textAlign: 'right' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={7} style={{ textAlign: 'center', padding: '60px 16px', color: '#64748B' }}>
                    <FileText size={40} color="#94A3B8" style={{ margin: '0 auto 12px', display: 'block' }} />
                    <div style={{ fontWeight: 700, fontSize: 16, color: '#0F172A' }}>No matching reports found</div>
                    <div style={{ fontSize: 13, marginTop: 4, color: '#64748B' }}>Try adjusting your search criteria or category filter.</div>
                  </td>
                </tr>
              ) : (
                filtered.map(r => (
                  <tr
                    key={r.id}
                    style={{
                      borderBottom: '1px solid #E2E8F0',
                      transition: 'background 0.15s ease',
                      background: '#FFFFFF',
                    }}
                  >
                    {/* Report ID & Title */}
                    <td style={{ padding: '14px 18px', verticalAlign: 'middle' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                        <div style={{
                          width: 36,
                          height: 36,
                          borderRadius: 8,
                          background: r.format === 'PDF' ? '#EFF6FF' : '#F0FDF4',
                          border: `1px solid ${r.format === 'PDF' ? '#BFDBFE' : '#BBF7D0'}`,
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          color: r.format === 'PDF' ? '#2563EB' : '#16A34A',
                          flexShrink: 0,
                        }}>
                          <FileText size={18} />
                        </div>
                        <div>
                          <div style={{ fontWeight: 700, color: '#0F172A', fontSize: 13.5 }}>
                            {r.title}
                          </div>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 3 }}>
                            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5, fontWeight: 700, color: '#2563EB' }}>
                              {r.id}
                            </span>
                            <span style={{ fontSize: 11, color: '#94A3B8' }}>•</span>
                            <span style={{ fontSize: 11.5, color: '#64748B' }}>{r.size}</span>
                          </div>
                        </div>
                      </div>
                    </td>

                    {/* Category */}
                    <td style={{ padding: '14px', verticalAlign: 'middle' }}>
                      <span style={{
                        display: 'inline-block',
                        padding: '3px 9px',
                        borderRadius: 6,
                        fontSize: 11,
                        fontWeight: 700,
                        background: '#F1F5F9',
                        border: '1px solid #E2E8F0',
                        color: '#475569',
                      }}>
                        {r.category}
                      </span>
                    </td>

                    {/* Generated Timestamp */}
                    <td style={{ padding: '14px', verticalAlign: 'middle', fontSize: 12, color: '#475569' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
                        <Calendar size={13} color="#94A3B8" />
                        <span>{r.generated_at}</span>
                      </div>
                    </td>

                    {/* Generated By */}
                    <td style={{ padding: '14px', verticalAlign: 'middle', fontSize: 12, color: '#64748B' }}>
                      {r.generated_by}
                    </td>

                    {/* Format */}
                    <td style={{ padding: '14px', verticalAlign: 'middle' }}>
                      <span style={{
                        fontSize: 10.5,
                        fontWeight: 700,
                        fontFamily: 'var(--font-mono)',
                        background: r.format === 'PDF' ? '#EFF6FF' : '#F0FDF4',
                        border: `1px solid ${r.format === 'PDF' ? '#BFDBFE' : '#BBF7D0'}`,
                        padding: '2px 7px',
                        borderRadius: 4,
                        color: r.format === 'PDF' ? '#2563EB' : '#16A34A',
                      }}>
                        {r.format === 'PDF' ? 'PDF / HTML' : 'CSV'}
                      </span>
                    </td>

                    {/* Status */}
                    <td style={{ padding: '14px', verticalAlign: 'middle' }}>
                      <span style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: 4,
                        padding: '3px 8px',
                        borderRadius: 6,
                        fontSize: 11,
                        fontWeight: 700,
                        background: '#F0FDF4',
                        border: '1px solid #86EFAC',
                        color: '#16A34A',
                      }}>
                        <Check size={11} /> {r.status}
                      </span>
                    </td>

                    {/* Actions */}
                    <td style={{ padding: '14px 18px', textAlign: 'right', verticalAlign: 'middle' }}>
                      <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                        {r.format === 'PDF' && (
                          <button
                            onClick={() => handleOpenPreview(r)}
                            style={{
                              fontSize: 11.5,
                              fontWeight: 600,
                              padding: '5px 9px',
                              borderRadius: 6,
                              background: '#F8FAFC',
                              border: '1px solid #CBD5E1',
                              color: '#0F172A',
                              cursor: 'pointer',
                              display: 'inline-flex',
                              alignItems: 'center',
                              gap: 4,
                            }}
                            title="Interactive Template Preview"
                          >
                            <Eye size={13} color="#2563EB" /> Preview
                          </button>
                        )}

                        {r.format === 'PDF' && (
                          <button
                            onClick={() => handlePrint(r)}
                            style={{
                              fontSize: 11.5,
                              fontWeight: 600,
                              padding: '5px 9px',
                              borderRadius: 6,
                              background: '#EFF6FF',
                              border: '1px solid #BFDBFE',
                              color: '#2563EB',
                              cursor: 'pointer',
                              display: 'inline-flex',
                              alignItems: 'center',
                              gap: 4,
                            }}
                            title="Print / Save as PDF"
                          >
                            <Printer size={13} /> Print / PDF
                          </button>
                        )}

                        <button
                          onClick={() => handleDownload(r)}
                          style={{
                            fontSize: 11.5,
                            fontWeight: 600,
                            padding: '5px 11px',
                            borderRadius: 6,
                            background: '#0F172A',
                            border: 'none',
                            color: '#FFFFFF',
                            cursor: 'pointer',
                            display: 'inline-flex',
                            alignItems: 'center',
                            gap: 5,
                            boxShadow: '0 1px 2px rgba(0,0,0,0.1)',
                          }}
                          title={`Download official ${r.format === 'PDF' ? 'PDF' : 'CSV'} report`}
                        >
                          <Download size={13} /> Download {r.format === 'PDF' ? 'PDF' : 'CSV'}
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* ── Generate New Audit Report Modal ───────────────────────── */}
      {showGenerateModal && (
        <div style={{
          position: 'fixed',
          inset: 0,
          background: 'rgba(15, 23, 42, 0.45)',
          backdropFilter: 'blur(6px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 9999,
          padding: 16,
        }}>
          <div style={{
            width: '100%',
            maxWidth: 560,
            padding: 24,
            background: '#FFFFFF',
            borderRadius: 16,
            boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
            border: '1px solid #E2E8F0',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <div style={{ width: 36, height: 36, borderRadius: 10, background: '#EFF6FF', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <FileText size={20} color="#2563EB" />
                </div>
                <div>
                  <h3 style={{ fontSize: 17, fontWeight: 700, color: '#0F172A', margin: 0 }}>Generate New Audit Report</h3>
                  <p style={{ fontSize: 12, color: '#64748B', margin: 0 }}>Synthesize verified telemetry logs into an audit package</p>
                </div>
              </div>
              <button
                onClick={() => setShowGenerateModal(false)}
                style={{ background: 'none', border: 'none', color: '#94A3B8', cursor: 'pointer', padding: 4 }}
              >
                <X size={18} />
              </button>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#475569', marginBottom: 6 }}>
                  Report Template Title
                </label>
                <select
                  value={newTitle}
                  onChange={e => {
                    setNewTitle(e.target.value)
                    if (e.target.value.includes('EV Battery')) setNewCategory('EV Fleet')
                    else if (e.target.value.includes('Cost') || e.target.value.includes('ROI')) setNewCategory('Financial')
                    else if (e.target.value.includes('Vector') || e.target.value.includes('Fingerprint')) setNewCategory('ML Research')
                    else if (e.target.value.includes('Executive') || e.target.value.includes('Weekly')) setNewCategory('Executive')
                    else setNewCategory('Operational')
                  }}
                  style={{
                    width: '100%',
                    padding: '9px 12px',
                    borderRadius: 8,
                    background: '#FFFFFF',
                    border: '1px solid #CBD5E1',
                    fontSize: 13,
                    color: '#0F172A',
                    outline: 'none',
                  }}
                >
                  <option value="Daily Fleet Failure Risk & Predictive Dispatch Brief">Daily Fleet Failure Risk & Predictive Dispatch Brief</option>
                  <option value="Weekly 100k Connected Vehicle Health & Ingestion Audit">Weekly 100k Connected Vehicle Health & Ingestion Audit</option>
                  <option value="High-Dimensional Vector Fingerprint Accuracy Report">High-Dimensional Vector Fingerprint Accuracy Report</option>
                  <option value="Monthly EV Battery Degradation & SOH Benchmark">Monthly EV Battery Degradation & SOH Benchmark</option>
                  <option value="Preventive Downtime Cost Savings & ROI Ledger">Preventive Downtime Cost Savings & ROI Ledger</option>
                </select>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#475569', marginBottom: 6 }}>
                    Category
                  </label>
                  <input
                    value={newCategory}
                    readOnly
                    style={{
                      width: '100%',
                      padding: '9px 12px',
                      borderRadius: 8,
                      background: '#F8FAFC',
                      border: '1px solid #CBD5E1',
                      fontSize: 13,
                      color: '#475569',
                      boxSizing: 'border-box',
                    }}
                  />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#475569', marginBottom: 6 }}>
                    Output Format
                  </label>
                  <select
                    value={newFormat}
                    onChange={e => setNewFormat(e.target.value)}
                    style={{
                      width: '100%',
                      padding: '9px 12px',
                      borderRadius: 8,
                      background: '#FFFFFF',
                      border: '1px solid #CBD5E1',
                      fontSize: 13,
                      color: '#0F172A',
                      outline: 'none',
                    }}
                  >
                    <option value="PDF">Executive Print/PDF Package (HTML)</option>
                    <option value="CSV">Raw Tabular Ledger (CSV)</option>
                  </select>
                </div>
              </div>

              <div>
                <label style={{ display: 'block', fontSize: 12, fontWeight: 600, color: '#475569', marginBottom: 6 }}>
                  Fleet Target Scope
                </label>
                <select
                  value={newScope}
                  onChange={e => setNewScope(e.target.value)}
                  style={{
                    width: '100%',
                    padding: '9px 12px',
                    borderRadius: 8,
                    background: '#FFFFFF',
                    border: '1px solid #CBD5E1',
                    fontSize: 13,
                    color: '#0F172A',
                    outline: 'none',
                  }}
                >
                  <option value="All Fleets (100,000 Connected Commercial Vehicles)">All Fleets (100,000 Connected Commercial Vehicles)</option>
                  <option value="Chennai Metro Depot (28,450 Heavy Commercial Units)">Chennai Metro Depot (28,450 Heavy Commercial Units)</option>
                  <option value="Bangalore Technology Corridor (24,120 EV Units)">Bangalore Technology Corridor (24,120 EV Units)</option>
                  <option value="Mumbai Western Freight Line (22,890 Cargo Units)">Mumbai Western Freight Line (22,890 Cargo Units)</option>
                  <option value="Delhi NCR Transit Zone (24,540 Mixed Units)">Delhi NCR Transit Zone (24,540 Mixed Units)</option>
                </select>
              </div>

              <div style={{ background: '#F8FAFC', padding: 12, borderRadius: 8, border: '1px solid #E2E8F0', fontSize: 12, color: '#64748B' }}>
                <span style={{ fontWeight: 600, color: '#0F172A' }}>Audit Guarantee:</span> The compiled document includes an ISO 26262 ASIL-D digital verification hash, telemetry anomaly breakdown, and sign-off blocks.
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 10, marginTop: 8 }}>
                <button
                  onClick={() => setShowGenerateModal(false)}
                  style={{
                    padding: '9px 16px',
                    borderRadius: 8,
                    background: '#F1F5F9',
                    border: '1px solid #E2E8F0',
                    color: '#475569',
                    fontSize: 13,
                    fontWeight: 600,
                    cursor: 'pointer',
                  }}
                >
                  Cancel
                </button>
                <button
                  onClick={handleConfirmGenerate}
                  disabled={generating}
                  style={{
                    padding: '9px 18px',
                    borderRadius: 8,
                    background: '#2563EB',
                    border: 'none',
                    color: '#FFFFFF',
                    fontSize: 13,
                    fontWeight: 600,
                    cursor: 'pointer',
                    boxShadow: '0 1px 3px rgba(37,99,235,0.3)',
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: 6,
                  }}
                >
                  {generating ? <RefreshCw size={14} className="spin" /> : <Plus size={14} />}
                  {generating ? 'Compiling Dossier...' : 'Compile Audit Package'}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ── Interactive Report Preview Modal ──────────────────────── */}
      {previewReport && (
        <div style={{
          position: 'fixed',
          inset: 0,
          background: 'rgba(15, 23, 42, 0.65)',
          backdropFilter: 'blur(8px)',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 9999,
          padding: 20,
        }}>
          <div style={{
            width: '100%',
            maxWidth: 960,
            height: '92vh',
            background: '#FFFFFF',
            borderRadius: 16,
            boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
            border: '1px solid #E2E8F0',
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden',
          }}>
            {/* Modal Header */}
            <div style={{
              padding: '14px 20px',
              borderBottom: '1px solid #E2E8F0',
              background: '#0F172A',
              color: '#FFFFFF',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <FileText size={18} color="#60A5FA" />
                <div>
                  <div style={{ fontSize: 14, fontWeight: 700 }}>
                    {previewReport.title}
                  </div>
                  <div style={{ fontSize: 11, color: '#94A3B8' }}>
                    {previewReport.id} • {previewReport.generated_at}
                  </div>
                </div>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                <button
                  onClick={() => openReportPrintWindow(previewReport.html)}
                  style={{
                    fontSize: 12,
                    fontWeight: 600,
                    padding: '6px 14px',
                    borderRadius: 6,
                    background: '#2563EB',
                    border: 'none',
                    color: '#FFFFFF',
                    cursor: 'pointer',
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: 6,
                  }}
                >
                  <Printer size={13} /> Print / Save as PDF
                </button>
                <button
                  onClick={() => handleDownload(previewReport)}
                  style={{
                    fontSize: 12,
                    fontWeight: 600,
                    padding: '6px 14px',
                    borderRadius: 6,
                    background: '#16A34A',
                    border: 'none',
                    color: '#FFFFFF',
                    cursor: 'pointer',
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: 6,
                  }}
                >
                  <Download size={13} /> Download Official PDF
                </button>
                <button
                  onClick={() => setPreviewReport(null)}
                  style={{
                    background: 'none',
                    border: 'none',
                    color: '#94A3B8',
                    cursor: 'pointer',
                    padding: 4,
                  }}
                >
                  <X size={20} />
                </button>
              </div>
            </div>

            {/* Modal Iframe Content */}
            <iframe
              srcDoc={previewReport.html}
              title="Report Preview"
              style={{
                width: '100%',
                flex: 1,
                border: 'none',
                background: '#F1F5F9',
              }}
            />
          </div>
        </div>
      )}
    </div>
  )
}

